[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "py5canvas"
version = "1.3.0"
description = "Drawings and animations with a p5.js / Processing-like API."
readme = { file = "README.md", content-type = "text/markdown" }
license = { text = "MIT" }
authors = [{ name = "Daniel Berio", email = "drand48@gmail.com" }]
requires-python = ">=3.9"
dependencies = [
  "numpy",
  "pillow",
  "opencv-python",
  "moderngl",
  "glfw",
  "pycairo",
  "pyperclip",
  "matplotlib",
  "rumore",
  "easydict",
  "xdialog",
  "slimgui",
  "platformdirs",
  "fonttools",
  "svgpathtools"
]

[project.scripts]
py5sketch = "py5canvas.run_sketch:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["py5canvas*"]
