# Autogenerated canvas/sketch methods as globals to trick the linter
# Generated from canvas.py and run_sketch.py


import numpy as np
from .globals import *
from .canvas import Canvas

__all__ = [
    "Image",
    "angle_mode",
    "apply_matrix",
    "arc",
    "arrow",
    "background",
    "begin_contour",
    "begin_shape",
    "bezier_vertex",
    "blend_mode",
    "blue",
    "brightness",
    "canvas_display_height",
    "canvas_display_width",
    "center",
    "check_reload",
    "circle",
    "cleanup",
    "clicked",
    "color_mode",
    "copy",
    "create_canvas",
    "create_canvas_gui",
    "create_glcontext",
    "create_graphics",
    "create_turtle",
    "cur_fill",
    "cur_stroke",
    "current_canvas",
    "curve",
    "curve_tightness",
    "curve_vertex",
    "delta_time",
    "description",
    "dragging",
    "ellipse",
    "ellipse_mode",
    "end_contour",
    "end_shape",
    "fill",
    "fill_rule",
    "finalize_grab",
    "frame",
    "frame_count",
    "frame_rate",
    "fullscreen",
    "get_buffer",
    "get_grayscale_array",
    "get_height",
    "get_image",
    "get_image_array",
    "get_image_grayscale",
    "get_origin",
    "get_pixel_ratio",
    "get_width",
    "grab",
    "grab_gif",
    "grab_image_sequence",
    "grab_movie",
    "green",
    "has_error",
    "height",
    "hsb",
    "hue",
    "identity",
    "image",
    "key",
    "key_is_down",
    "lightness",
    "line",
    "linear_gradient",
    "linear_gradient_angle",
    "load",
    "millis",
    "mouse_is_pressed",
    "mouse_x",
    "mouse_y",
    "multibezier",
    "no_fill",
    "no_loop",
    "no_stroke",
    "no_tint",
    "num_movie_frames",
    "open_file_dialog",
    "open_folder_dialog",
    "param_changed",
    "point",
    "polygon",
    "polyline",
    "pop",
    "pop_matrix",
    "pop_style",
    "push",
    "push_matrix",
    "push_style",
    "quad",
    "radial_gradient",
    "read_fb",
    "rect",
    "rect_mode",
    "rectangle",
    "red",
    "reset_matrix",
    "rgb",
    "rotate",
    "rotate_deg",
    "saturation",
    "save",
    "save_canvas",
    "save_copy",
    "save_file_dialog",
    "save_image",
    "save_pdf",
    "save_svg",
    "scale",
    "seconds",
    "send_osc",
    "set_color_scale",
    "set_floating",
    "set_gui_callback",
    "set_gui_theme",
    "shape",
    "show",
    "show_gui",
    "show_plt",
    "square",
    "start_osc",
    "stop_grabbing",
    "stroke",
    "stroke_cap",
    "stroke_dash",
    "stroke_join",
    "stroke_weight",
    "surface",
    "text",
    "text_align",
    "text_bounds",
    "text_font",
    "text_height",
    "text_leading",
    "text_points",
    "text_shape",
    "text_shapes",
    "text_size",
    "text_style",
    "text_width",
    "tint",
    "title",
    "to_clipboard",
    "toggle_fullscreen",
    "toggle_gui",
    "translate",
    "triangle",
    "update_globals",
    "vertex",
    "width",
]

def set_color_scale(scale):
    """Set color scale:

Arguments:

- `scale` (float): the color scale. if we want to specify colors in the `0...255` range,
 `scale` will be `255`. If we want to specify colors in the `0...1` range, `scale` will be `1`"""
    ...

cur_fill: np.ndarray = None  # property

cur_stroke: np.ndarray = None  # property

# The center of the canvas (as a 2d numpy array)
center: np.ndarray = None  # property

def get_width()  -> int:
    """The width of canvas"""
    ...

def get_height()  -> int:
    """The height of canvas"""
    ...

# The width of canvas
width: int = None  # property

# The height of canvas
height: int = None  # property

surface = None  # property

def no_fill():
    """Do not fill subsequent shapes"""
    ...

def no_stroke():
    """Do not stroke subsequent shapes"""
    ...

def no_tint():
    """Do not tint images"""
    ...

def fill_rule(rule):
    """Sets the fill rule for complex shapes.

Arguments:
- One of `"evenodd"`, `"nonzero"`, or `"winding"`"""
    ...

def angle_mode(mode= 'degrees'):
    ...

def color_mode(mode, *args):
    """Set the color mode for the canvas
- `mode` (string): can be one of 'rgb', 'hsv' depending on the desired color mode
- `scale` (float): the scale for the color values (e.g. 255 for 0...255 range, 1 for 0...1 range)
- `*args`: color values in the current color mode

Examples:

- `color_mode('rgb', 1.0)` will set the color mode to RGB in the 0-1 range.

Returns:

- (float): red component value in the current color scale"""
    ...

def red(*args)  -> float:
    """Return the red component of a color.

Arguments:

- `*args`: color values in the current color mode

Returns:

- (float): red component value in the current color scale"""
    ...

def green(*args)  -> float:
    """Return the green component of a color.

Arguments:

- `*args`: color values in the current color mode

Returns:

- (float): green component value in the current color scale"""
    ...

def blue(*args)  -> float:
    """Return the blue component of a color.

Arguments:

- `*args`: color values in the current color mode

Returns:

- (float): blue component value in the current color scale"""
    ...

def hue(*args)  -> float:
    """Return the hue component of a color.

Arguments:

- `*args`: color values in the current color mode

Returns:

- (float): hue component value in the current color scale"""
    ...

def saturation(*args)  -> float:
    """Return the saturation component of a color.

Arguments:

- `*args`: color values in the current color mode

Returns:

- (float): saturation component value in the current color scale"""
    ...

def lightness(*args)  -> float:
    """Return the lightness component of a color.

Arguments:

- `*args`: color values in the current color mode

Returns:

- (float): lightness component value in the current color scale"""
    ...

def brightness(*args)  -> float:
    """Return the brightness component of a color.

Arguments:

- `*args`: color values in the current color mode

Returns:

- (float): brightness component value in the current color scale"""
    ...

def linear_gradient_angle(*args, extend= 'pad'):
    """Create a linear gradient fill.

Can be called in two ways:
    `linear_gradient(x1, y1, angle, length, stop1, stop2, ...)`
    `linear_gradient((x1, y1), angle, length, stop1, stop2, ...)`

Each stop is a tuple:
   `(offset, color)`
where:
    - offset is between 0 and 1
    - color is a tuple (r, g, b[, a]) in current color mode"""
    ...

def linear_gradient(*args, extend= 'pad'):
    """Create a linear gradient fill.

Can be called in two ways:
    `linear_gradient(x1, y1, x2, y2, stop1, stop2, ...)`
    `linear_gradient((x1, y1), (x2, y2), stop1, stop2, ...)`

Each stop is a tuple:
   `(offset, color)`
where:
    - offset is between 0 and 1
    - color is a tuple (r, g, b[, a]) in current color mode

Example:
```
    fill(linear_gradient(0, 0, 200, 0,
                        (0, (1, 0, 0)),
                        (1, (0, 0, 1))))
```"""
    ...

def radial_gradient(*args, extend= 'pad'):
    """Create a radial gradient fill.

Can be called in two ways:
    `radial_gradient(cx0, cy0, r0, cx1, cy1, r1, stop1, stop2, ...)`
    `radial_gradient((cx0, cy0, r0), (cx1, cy1, r1), stop1, stop2, ...)`

- (cx0, cy0, r0): center and radius of the inner circle
- (cx1, cy1, r1): center and radius of the outer circle

Each stop is a tuple:
    (offset, color)
where:
    - offset is between 0 and 1
    - color is a tuple (r, g, b[, a]) in current color mode

Example:
```
    fill(radial_gradient((100, 100, 0), (100, 100, 80),
                        (0, (1, 1, 1)),
                        (1, (0, 0, 0))))
```"""
    ...

def tint(*args):
    """Set the tint color for images

Arguments:
- A single argument specifies a grayscale value, e.g. `stroke(255)` will set the stroke to white.
- Two arguments specify grayscale with opacity, e.g. `stroke(0, 128)` will set the stroke to black with 50% opacity.
- Three arguments specify a color depending on the color mode (rgb or hsv), e.g. `stroke(255, 0, 0)` will set the stroke to red, when the color mode is RGB
- Four arguments specify a color with opacity"""
    ...

def fill(*args):
    """Set the color of the current fill

Arguments:

- A single argument specifies a grayscale value, e.g `fill(128)` will fill with 50% gray.
- Two arguments specify grayscale with opacity, e.g. `fill(255, 128)` will fill with transparent white.
- Three arguments specify a color depending on the color mode (rgb or hsv)
- Four arguments specify a color with opacity"""
    ...

def stroke(*args):
    """Set the color of the current stroke

Arguments:
- A single argument specifies a grayscale value, e.g. `stroke(255)` will set the stroke to white.
- Two arguments specify grayscale with opacity, e.g. `stroke(0, 128)` will set the stroke to black with 50% opacity.
- Three arguments specify a color depending on the color mode (rgb or hsv), e.g. `stroke(255, 0, 0)` will set the stroke to red, when the color mode is RGB
- Four arguments specify a color with opacity"""
    ...

def stroke_dash(dash):
    """Set the line dash (stippling)

Arguments:
- A sequence of lengths, indicating alternating (on/off) dashed segments"""
    ...

def stroke_weight(w):
    """Set the line width

Arguments:
- The width in pixel of the stroke"""
    ...

def stroke_join(join):
    '''Specify the 'join' mode for polylines.

Arguments:

- `join` (string): can be one of "miter", "bevel" or "round"'''
    ...

def blend_mode(mode= 'over'):
    """Specify the blending mode

Arguments:

- `mode` (string) can be a one of the blend mode constants:
    - `BLEND = "over"` (default) - Source overwrites canvas
    - `REPLACE = "source"` - Source completely replaces canvas
    - `ADD = "add"` - Source colors added to canvas
    - `MULTIPLY = "multiply"` - Colors multiplied (always darker)
    - `SCREEN = "screen"` - Colors inverted, multiplied, then inverted (always lighter)
    - `OVERLAY = "overlay"` - MULTIPLY for dark areas, SCREEN f
    - `DARKEST = "darken"` - Keeps the darker color value
    - `LIGHTEST = "lighten"` - Keeps the lighter color value
    - `DIFFERENCE = "difference"` - Canvas minus source (absolute value)
    - `EXCLUSION = "exclusion"` - Similar to DIFFERENCE but lower contrast
    - `HARD_LIGHT = "hard_light"` - Like OVERLAY but based on source brightness
    - `SOFT_LIGHT = "soft_light"` - Softer version of HARD_LIGHT
    - `DODGE = "color_dodge"` - Lightens and increases contrast
    - `BURN = "color_burn"` - Darkens and increases contrast
    - `REMOVE = "clear"` - Overlapping pixels become transparent

  or a string, one of: "clear", "source", "over", "in", "out", "atop",
  "dest", "dest_over", "dest_in", "dest_out", "dest_atop", "xor", "add", "saturate", "multiply", "screen", "overlay", "darken", "lighten", "color_dodge", "color_burn", "hard_light", "soft_light", "difference", "exclusion", "hsl_hue", "hsl_saturation", "hsl_color", "hsl_luminosity".
  See [Cairo Graphics Operators](https://www.cairographics.org/operators/) for a discussion on the different operators."""
    ...

def stroke_cap(cap):
    '''Specify the 'cap' for lines.

Arguments:

- `cap` (string): can be one of "butt", "round" or "square"'''
    ...

def text_align(halign, valign= 'bottom'):
    '''Specify the text alignment.

Arguments:
- `halign` (string): Horizontal alignment. One of "left", "center" or "right"
- `valign` (string): Horizontal alignment. One of "baseline" (default), "top", "bottom", or "center"'''
    ...

def text_size(size):
    """Specify the text size

N.B. this will also reset the text leading

Arguments:

- `size` (int): the text size"""
    ...

def text_leading(*args):
    """Specify the space between consecutive lines of text
if no arguments are specified, returns the text leading values.

Arguments:

- `leading` (int, optional): the text leading"""
    ...

def text_font(font):
    """Specify the font to use for text rendering.

Arguments:

- `font` (string or object): Either a string describing the font file path or system font name, or a font object (created with `create_font`)"""
    ...

def text_style(style):
    """Specify the style (normal, italic, bold, bolditalic) to use for text
rendering.

Arguments:
- `style` (string): the name of a style ("normal", "italic", "bold",
"bolditalic")"""
    ...

def text_width(txt):
    ...

def text_height(txt):
    ...

def push_matrix():
    """Save the current transformation"""
    ...

def pop_matrix():
    """Restore the previous transformation"""
    ...

def push_style():
    """Save the current drawing state"""
    ...

def pop_style():
    """Restore the previously pushed drawing state"""
    ...

def push():
    """Save the current drawing state and transformations"""
    ...

def pop():
    """Restore the previously pushed drawing state and transformations"""
    ...

def translate(*args):
    """Translate by specifying `x` and `y` offset.

Arguments:

- The offset can be specified as an array/list (e.g `translate([x,y])`
  or as single arguments (e.g. `translate(x, y)`)"""
    ...

def scale(*args):
    """Apply a scaling transformation.

Arguments:

- Providing a single number will apply a uniform transformation.
- Providing a pair of number will scale in the x and y directions.
- The scale can be specified as an array/list (e.g `scale([x,y])`
or as single arguments (e.g. `scale(x, y)`)'''"""
    ...

def rotate(angle):
    """Rotate by `theta` radians (or degrees, depeending on the angle mode)"""
    ...

def apply_matrix(mat):
    """Apply an affine (3x3) transformation matrix"""
    ...

def get_origin():
    """Get the origin in canvas coordinates for the current transformation.
Returns a 2d numpy array"""
    ...

def rotate_deg(deg):
    """Rotate using degrees"""
    ...

def hsb(*args):
    """Return RGB components for a color defined as HSB"""
    ...

def rgb(*args):
    """Return HSV components for a color defined as RGB"""
    ...

def begin_shape():
    """Start building a complex shape. Drawing is deferred until end_shape()."""
    ...

def end_shape(close= False):
    """Finish the shape and draw it."""
    ...

def begin_contour():
    """Start a new contour within the currently built shape.
If no shape is active, a new one is created automatically."""
    ...

def end_contour(close= False):
    """End the current contour. If not inside a begin_shape/end_shape block,
the contour is drawn immediately.

Arguments:

- `close` (bool, optional): if `True` close the contour"""
    ...

def vertex(x, y= None):
    """Add a vertex to current contour

Input arguments can be in the following formats:

- `[x, y]`
- `x, y`"""
    ...

def curve_vertex(x, y= None):
    """Add a curved vertex to current contour

Input arguments can be in the following formats:

- `[x, y]`
- `x, y`"""
    ...

def bezier_vertex(*args):
    """Draw a cubic Bezier segment from the current point
requires a first control point to be already defined with `vertex`.


Requires three points. Input arguments can be in the following formats:

- `[x1, y1], [x2, y2], [x3, y3]`
- `x1, y1, x2, y2, x3, y3`"""
    ...

def curve_tightness(val):
    """Sets the 'tension' parameter for the curve used when using `curve_vertex`"""
    ...

def shape(obj, close= False):
    """Draw a pre‑built Shape object or a list of polylines (list of lists/arrays).
For lists, each polyline becomes one contour (open or closed)."""
    ...

def rect_mode(mode):
    """Set the "mode" for drawing rectangles.

Arguments:
- `mode` (string): can be one of 'corner', 'corners', 'center', 'radius'"""
    ...

def ellipse_mode(mode):
    """Set the "mode" for drawing rectangles.

Arguments:
- `mode` (string): can be one of 'corner', 'center'"""
    ...

def rectangle(*args, mode= None):
    """Draw a rectangle.
Can use `rect` equivalently.

Arguments:
The first sequence of arguments is one of

 - `[x, y], [width, height]`,
 - `[x, y], width, height`,
 - `x, y, width, height`
 - `[[topleft_x, topleft_y], [bottomright_x, bottomright_y]]`

Followed by an optional radius parameter that can be used to create rounded rectangles

An optional named `mode` argument allows to ignore the current rect mode since it explictly defines the
corners of the rect

The interpretation of `x` and `y` depends on the current rect mode.
These indicate the center of the rectangle if the rect mode is
`"center"` or `"radius"` and the top-left corner otherwise."""
    ...

def square(*args, mode= None):
    """Draw a square.

Arguments:

The first sequence of arguments is one of
 - `[x, y], size`,
 - `x, y, size`

The interpretation of `x` and `y` depends on the current rect mode. These indicate the
center of the rectangle if the rect mode is `"center"` and the top left corner otherwise."""
    ...

def rect(*args, mode= None):
    """Draws a rectangle.

Input arguments can be in the following formats:

 - `[topleft_x, topleft_y], [width, height]`,
 - `[topleft_x, topleft_y], width, height`,
 - `topleft_x, topleft_y, width, height`

Depending on"""
    ...

def quad(*args):
    """Draws a quadrangle given four points

Input arguments can be in the following formats:

 - `a, b, c, d` (Four points specified as lists/tuples/numpy arrays
 - `x1, y1, x2, y2, x3, y3, x4, y4`, a sequence of numbers, one for each coordinate"""
    ...

def triangle(*args):
    """Draws a triangle given three points

Input arguments can be in the following formats:

 - `a, b, c` (Four points specified as lists/tuples/numpy arrays
 - `x1, y1, x2, y2, x3, y3`"""
    ...

def circle(*args, mode= ''):
    """Draw a circle given center and radius

Input arguments can be in the following formats:

- `[center_x, center_y], radius`,
- `center_x, center_y, raidus`"""
    ...

def ellipse(*args, mode= None):
    """Draw an ellipse with center, width and height.

Input arguments can be in the following formats:

- `[center_x, center_y], [width, height]`,
- `[center_x, center_y], width, height`,
- `center_x, center_y, width, height`
- `[center_x, center_y], width`,
- `center_x, center_y, width`,"""
    ...

def line(*args):
    """Draws a line between two points

Input arguments can be in the following formats:

 - `a, b` (Two points specified as lists/tuples/numpy arrays
 - `x1, y1, x2, y2`, a sequence of numbers, one for each coordinate"""
    ...

def point(*args):
    """Draw a point at a given position

Input arguments can be in the following formats:

 - `[x, y]`: a single point specified as a tuple/list/numpy array
 - `x1, y1`: two coordinates"""
    ...

def arrow(*args, size= 2.5, overhang= 0.7, length= 2.0):
    """Draw an arrow between two points

Input arguments can be in the following formats:

- `a, b` (Two points specified as lists/tuples/numpy arrays
- `x1, y1, x2, y2`, a sequence of numbers, one for each coordinate"""
    ...

def arc(*args):
    """Draw an ellpitical arc, given the center of the ellipse `x, y`
the size of the ellipse `w, h` and the initial and final angles
in radians  `start, stop`.
A last optional `mode` argument determines the arc's fill style.
The fill modes are a semi-circle (`OPEN`), a closed semi-circle (`CHORD`),
or a closed pie segment (`PIE`).

Input arguments can be in the following formats:

  - `x, y, w, h, start, stop`
  - `[x, y]`, `[w, h]`, `[start, stop]`
  - `[x, y]`, `w, h, start, stop`"""
    ...

def polygon(*args, close= True):
    """Draw a polygon (closed by default).

The polyline is specified as either:

- a list of =[x,y]= pairs (e.g. =[[0, 100], [200, 100], [200, 200]]=)
- a numpy array with shape =(n, 2)=, representing =n= points (a point for each row and a coordinate for each column)
- two lists (or numpy array) of numbers, one for each coordinate

To create an opne polygon set the named =close= argument to =False=, e.g. =c.polygon(points, close=False)=."""
    ...

def polyline(*args, close= False):
    """Draw a polyline (open by default).

The polyline is specified as either:

- a list of =[x,y]= pairs (e.g. =[[0, 100], [200, 100], [200, 200]]=)
- a numpy array with shape =(n, 2)=, representing =n= points (a point for each row and a coordinate for each column)
- two lists (or numpy array) of numbers, one for each coordinate

To close the polyline set the named =close= argument to =True=, e.g. =c.polyline(points, close=True)=."""
    ...

def multibezier(*args, close= False):
    """Draw a sequence of connected cubic Bézier curves.

Input can be:
- a list of [x,y] pairs: first point is start, then triples of control points
  (c1, c2, end) for each segment.
- two lists (or numpy arrays) of x, y coordinates, similarly arranged.
- a flat list of coordinates."""
    ...

def curve(*args, close= False):
    """Draw a curve (open by default) using Cardinal spline interpolation.

The polyline is specified as either:

- a list of =[x,y]= pairs (e.g. =[[0, 100], [200, 100], [200, 200]]=)
- a numpy array with shape =(n, 2)=, representing =n= points (a point for each row and a coordinate for each column)
- two lists (or numpy array) of numbers, one for each coordinate

To close the curve set the named =close= argument to =True=, e.g. =c.curve(points, close=True)=."""
    ...

def identity():
    """Resets the current matrix to the identity (no transformation)"""
    ...

def reset_matrix():
    """Resets the current matrix to the identity (no transformation)"""
    ...

def copy(*args):
    """The first parameter can optionally be an image, if an image is not specified the funtion will use
the canvas image, .
The next four parameters, sx, sy, sw, and sh determine the region to copy from the source image.
(sx, sy) is the top-left corner of the region. sw and sh are the region's width and height.
The next four parameters, dx, dy, dw, and dh determine the region of the canvas to copy into.
(dx, dy) is the top-left corner of the region. dw and dh are the region's width and height.

`copy(src_image, sx, sy, sw, sh, dx, dy, dw, dh)`
or
`copy(sx, sy, sw, sh, dx, dy, dw, dh)`"""
    ...

def background(*args):
    """Clear the canvas with a given color
Accepts either an array with the color components, or single color components (as in `fill`)"""
    ...

def get_buffer():
    ...

def get_image_array():
    """Get canvas image as a numpy array"""
    ...

def get_grayscale_array():
    """Get grayscale image of canvas contents as float numpy array (0 to 1 range)"""
    ...

def get_image():
    """Get canvas as a PIL image"""
    ...

def get_image_grayscale():
    """Returns the canvas image as a grayscale numpy array (in 0-1 range)"""
    ...

def save_image(path):
    """Save the canvas to an image

Arguments:

- The path where to save"""
    ...

def save_svg(path):
    """Save the canvas to an svg file

Arguments:

- The path where to save"""
    ...

def save_pdf(path):
    """Save the canvas to an svg file

Arguments:

- The path where to save"""
    ...

def Image():
    ...

def to_clipboard():
    """Copy canvas contents to clipboard (as SVG data)
Requires pyperclip to be installed"""
    ...

def save(path):
    """Save the canvas into a given file path
The file format depends on the file extension"""
    ...

def show(size= None, resample= 'bicubic'):
    """Display the canvas in a notebook"""
    ...

def show_plt(size= None, title= '', axis= False):
    """Show the canvas in a notebook with matplotlib

Arguments:

- `size` (tuple, optional): The size of the displayed image, by default this is the size of the canvas
- `title` (string, optional): A title for the figure
- `axis` (bool, optional): If `True` shows the coordinate axes"""
    ...

def create_turtle(*args, autodraw= True):
    """Create a turtle object at a given position (default is the origin)

Arguments:
- Optional, a pair of initial coordinates (either two values or a tuple/vector). The default is (0, 0)
- `autodraw` (`bool`, default `True`): if `True` automatically draws the turtle path if the pen is down"""
    ...

def create_graphics(w, h):
    """Create a new canvas with the specified width and height
E.g. `c = create_graphics(128, 128)` will put a new canvas into
the variable `c`. You can draw the contents of the canvas with the `image` function."""
    ...

def image(img, *args, opacity= 1.0):
    """Draw an image at position with (optional) size and (optional) opacity

Arguments:

- `img`: The input image. Can be either a PIL image, a numpy array, a Canvas or a pyCairo surface.
- optional arguments: position and size can be specified with the following formats:
    - `x, y`:  position only
    - `x, y, w, h`: position and size
    - `[x, y]`: position only (also a numpy array or tuple are valid)
    - `[x, y], [w, h]`: position and size
if the position is not specified, the original image dimensions will be used

- `opacity`: a value between 0 and 1 specifying image opacity."""
    ...

def text(text, *args, align= '', valign= '', center= None, **kwargs):
    """Draw text at a given position

Arguments:

    - `text`, the text to display
    - the position of the text, either a pair of x, y arguments or a list like object (e.g. `[x, y]`)
    - `align`, horizontal alignment, etiher `'left'` (default), `'center'` or `'right'`
    - `valign`, vertical alignment, etiher `'bottom'` (default), `'center'` or `'top'`
    (Deprecated) if center=True the text will be horizontally centered"""
    ...

def text_shapes(text, *args, dist= 1, align= '', valign= ''):
    ...

def text_shape(text, *args, dist= 1, align= '', valign= ''):
    """Retrieves polylines for a given string of text in the current font

Arguments:

- `text`, the text to sample
- the position of the text, either a pair of x, y arguments or a list like object (e.g. `[x, y]`)
- `dist`, approximate distance between samples
- `align`, horizontal alignment, etiher `'left'` (default), `'center'` or `'right'`
- `valign`, vertical alignment, etiher `'bottom'` (default), `'center'` or `'top'`"""
    ...

def text_points(text, *args, dist= 1, align= '', valign= ''):
    """Retrieves points for a given string of text in the current font

Arguments:

- `text`, the text to sample
- the position of the text, either a pair of x, y arguments or a list like object (e.g. `[x, y]`)
- `dist`, approximate distance between samples
- `align` (named), horizontal alignment, etiher `'left'` (default), `'center'` or `'right'`
- `valign` (named), vertical alignment, etiher `'bottom'` (default), `'center'` or `'top'`"""
    ...

def text_bounds(text, *args, align= '', valign= ''):
    """Returns the bounding box of a string of text at a given position"""
    ...

def create_glcontext():
    ...

# The horizontal coordinate of the mouse position
mouse_x: int = None  # property

# The vertical coordinate of the mouse position
mouse_y: int = None  # property

# The number of frames since the script has loaded
frame_count: int = None  # property

def millis()  -> int:
    """The number of milliseconds since the script has loaded"""
    ...

def seconds()  -> float:
    """The number of seconds since the script has loaded"""
    ...

# Returns `True` if mouse was clicked
clicked: bool = None  # property

# Returns `True` if mouse is pressed
dragging: bool = None  # property

# Returns `True` if mouse is pressed
mouse_is_pressed: bool = None  # property

# Returns last key pressed
key: str = None  # property

def key_is_down(k)  -> bool:
    """Returns True if the key `k` is pressed"""
    ...

delta_time: float = None  # property

def has_error():
    ...

def open_file_dialog(exts, title= 'Open file…')  -> str:
    """Opens a dialog to select a file.
exts: 'png' or ['png', 'jpg'] (extensions without dots)
Returns the selected path (str) or '' if cancelled."""
    ...

def save_file_dialog(exts, title= 'Open file...', filename= 'untitled')  -> str:
    """Opens a dialog to select a file to be saved,
the first argument is the extension or the file to be saved,
e.g. `'png'` or a list of extensions, e.g. `['png', 'jpg']`

The function returns the path of the file if it is selected or an empty string othewise."""
    ...

def open_folder_dialog(title= 'Open folder...')  -> str:
    """Opens a dialog to select a folder/directory to be opened,

The function returns the path of the directory if it is selected or an empty string othewise."""
    ...

def create_canvas(w, h, gui_width= 300, fullscreen= False, with_gui= True, screen= None, save_background= True):
    ...

current_canvas = None  # property

canvas_display_width = None  # property

canvas_display_height = None  # property

def create_canvas_gui(w, h, width= 300, fullscreen= False, screen= None, save_background= False):
    ...

def get_pixel_ratio():
    ...

def save_canvas(path, copy= False):
    """Tells the sketch to dump the next frame to an SVG file"""
    ...

def toggle_gui(screen_index= -1):
    """Toggle between GUI and non-gui"""
    ...

def show_gui(flag, screen_index= -1):
    ...

def toggle_fullscreen(toggle_gui= False, screen_index= -1):
    """Toggle between fullscreen and windowed mode"""
    ...

def set_floating(flag):
    """Sets the sketch windo to floating or not"""
    ...

def fullscreen(flag, toggle_gui= False, screen_index= -1):
    """Sets fullscreen or windowed mode depending on the first argument (`True` or `False`)"""
    ...

def no_loop():
    """Stops the drawing loop keeping the last frame fixed on the canvas"""
    ...

def set_gui_theme(hue):
    ...

def set_gui_callback(func):
    ...

def param_changed(*args):
    ...

def load(path):
    ...

def grab_image_sequence(path, num_frames, reload= True):
    """Saves a sequence of image files to a directory, one for each frame.
By default this will reload the current script.

Arguments:
- `path` (string), the directory where to save the images
- `num_frames` (int), the number of frames to save
- `reload` (bool), whether to reload the sketch, default: True"""
    ...

def grab_gif(path, num_frames= 0, framerate= 30, gamma= 1.0, reload= True):
    ...

def grab_movie(path, num_frames= 0, framerate= 30, gamma= 1.0, reload= True):
    """Saves a mp4 movie from a number of frames to a specified path.
By default this will reload the current script.

Arguments:
- `path` (string), the directory where to save the video
- `num_frames` (int), the number of frames to save, default: 0
- `framerate` (int), the framerate, default: 30

- `gamma` (float), the gamma correction, default: 1.0 (see the [OpenCV docs](https://docs.opencv.org/4.x/d3/dc1/tutorial_basic_linear_transform.html))
- `reload` (bool), whether to reload the sketch, default: True"""
    ...

def stop_grabbing():
    ...

def grab():
    ...

def finalize_grab():
    ...

def save_copy(path):
    ...

def read_fb(fb, **kwargs):
    ...

def update_globals():
    """Inject globals that are not updated automatically"""
    ...

def check_reload():
    ...

def frame(draw_frame):
    ...

def title(title):
    """Sets the title of the sketch window"""
    ...

def description(text):
    """Set the description of the current sketch"""
    ...

def frame_rate(fps):
    """Set the framerate of the sketch in frames-per-second"""
    ...

def num_movie_frames(num):
    """Set the number of frames to export when saving a video"""
    ...

def start_osc(load_settings= True):
    ...

def send_osc(addr, val):
    """Send an OSC message"""
    ...

def cleanup():
    ...

